### ISSUE TITLE
mobile view

### ISSUE THREAD

**Issue by deadly115** [vaibhav-OP/manganerdy#1]
### Describe the bug

the website works good on laptop and the comics pages are fitted in well but in mobile the comic needs to be manually adusted or fixed so probably the dynamic element of the website is not working properly

### To Reproduce

add dynamic bheviour or check if you missed some lines 

### Expected behavior

should complete cover the screen of phone while reading comic

**Comment by vaibhav-OP** [comment]
Have fixed this issue, from what I understood.
Can you please confirm if it still exists and if so, please provide some screen shots of the problem you are facing for a better understanding of it.

**Comment by deadly115** [comment]
Let me check.
