### ISSUE TITLE
next and previoud chapter button 

### ISSUE THREAD

**Issue by deadly115** [vaibhav-OP/manganerdy#2]
### Is your feature request related to a problem? Please describe.

next and previous chapter button are missing please make them with top priority

### Describe the solution you'd like

next button and previous chapter button for each and every chapter same time the person can go to any chapter from the chapter chapter ex:from ch4 he can just go to any other chaper easily without going back to main page

### Describe alternatives you've considered

![image](https://user-images.githubusercontent.com/79560120/212552066-b0645c74-19ab-4c3f-8cdf-b61ef5ade839.png)
like this

**Comment by vaibhav-OP** [comment]
### **Feature ADDED** 
remember not to add chapters with same name on same comic (will cause problems)
