### ISSUE TITLE
most views and latest update not working 

### ISSUE THREAD

**Issue by deadly115** [vaibhav-OP/manganerdy#3]
### Describe the bug

latest update is not working and most views or recent trneding section is not working too and ps automatic slider

### To Reproduce

u can make it easy 

### Expected behavior

when i upload a comic it should show in latest updated which it is not showing

**Comment by vaibhav-OP** [comment]
### ISSUE
Latest Updated section's comics aren't sorted by latest updated but latest created .

### Reason
we wanted to sort the comics by the `chapters.updatedAt` not `updatedAt`.
