### ISSUE TITLE
addition of disqus

### ISSUE THREAD

**Issue by deadly115** [vaibhav-OP/manganerdy#4]
### Is your feature request related to a problem? Please describe.

currently the website is bit simple with the addition of disqus it will be interactive as users can like comment and interact 

### Describe the solution you'd like

Disqus offers the best add-on tools for websites to increase engagement. We help publishers power online discussions with comments and likes.

### Describe alternatives you've considered

if the plugin cant be added then we can work with custom comment section which might be bit complicated

**Comment by vaibhav-OP** [comment]
Looking forward to create own custom authentication system with comment section in **v2**.
